### ISSUE TITLE
Extend zxcc to work with MacOS

### ISSUE THREAD

**Issue by tsupplis** [agn453/ZXCC#42]
MacOS does not support /proc. The code in zxcc uses /proc to find out a potential location for bios.bin.
Here is a suggested fix
```
    if (!fp)
    {
        dir[0] = 0;                           /* use strncat in case the path is very long */
#ifdef _MSC_VER
        strncat(dir, _pgmptr, CPM_MAXPATH - 8);   /* copy the executable path */
#elif defined(__linux)  
        readlink("/proc/self/exe", dir, CPM_MAXPATH - 8);   /* allow room for bios.bin */
#endif
        if(dir[0]) {
            q = strrchr(dir, DIRSEPCH);
            *++q = 0;
            strcpy(fname, dir);
            strcat(fname, "bios.bin");
            fp = fopen(fname, "rb");
        }
    }
 ```

**Comment by agn453** [comment]
I use macOS but didn't notice this since I have the ```bios.bin``` file in the CP/M binaries subdirectory.

I modified your suggested fix to use the macOS _NSGetExecutablePath routine to get the executable pathname.  I think the code should work under Cygwin - if it doesn't, then there may be more tweaks required.

4157e2ea825ff93249eb7b09d70156b225b86f69
